import { Dimensions, StyleSheet } from 'react-native';
const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#1E1E1E',
    },
    loadingScreen: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#121212',
    },
    cameraContainer: {
      width: '100%',
      overflow: 'hidden',
      borderBottomLeftRadius: 32,
      borderBottomRightRadius: 32,
      backgroundColor: '#1E1E1E',
    },
    camera: {
      ...StyleSheet.absoluteFillObject,
    },
    resizeHandle: {
      position: 'absolute',
      width: 20,
      height: 20,
      bottom: -10,
      right: -10,
      backgroundColor: 'white',
      borderRadius: 10,
    },
    imageContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    capturedImage: {
      width: '100%',
      height: '100%',
      position: 'absolute',
    },
    croppedImage: {
      // width: '100%',
      // height: '100%',
      // position: 'absolute',
      // backgroundColor: 'blue',
      // opacity: 0.8
        ...StyleSheet.absoluteFillObject, flex: 1, resizeMode: 'contain' 
    },
    cropBox: {
      position: 'absolute',
      borderColor: 'white',
      borderWidth: 2,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      zIndex: 20,
    },
    glowingStar: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: [{ translateX: -25 }, { translateY: -25 }],
      zIndex: 50,
    },
    cropButton: {
      // position: 'absolute',
      // bottom: 50,
      // right: 50,
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      padding: 24,
      borderRadius: 36,
    },
    overlayContainer: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'space-between',
    },
    topBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      marginTop: 16,
    },
    topLeftCorner: {
      top: -2,
      left: -2,
      borderTopLeftRadius: 50,
      borderRightWidth: 0,
      borderBottomWidth: 0,
    },
    topRightCorner: {
      top: -2,
      right: -2,
      borderTopRightRadius: 50,
      borderLeftWidth: 0,
      borderBottomWidth: 0,
    },
    bottomLeftCorner: {
      bottom: -2,
      left: -2,
      borderBottomLeftRadius: 50,
      borderRightWidth: 0,
      borderTopWidth: 0,
    },
    bottomRightCorner: {
      bottom: -2,
      right: -2,
      borderBottomRightRadius: 50,
      borderLeftWidth: 0,
      borderTopWidth: 0,
    },
    lastIcon: {
      width: 36,
      height: 36,
    },
    title: {
      color: 'white',
      fontSize: 18,
      fontFamily: 'OpenSans-Bold',
    },
    iconButton: {
      padding: 8,
    },
    overlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    middleOverlay: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    sideOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    cropArea: {
      width: width * 0.7,
      height: width * 0.7,
      position: 'relative',
      backgroundColor: 'transparent',
    },
    // cropArea: {
    //     position: 'absolute',
    //     borderWidth: 2,
    //     borderColor: 'white',
    //     backgroundColor: 'rgba(255, 255, 255, 0.1)',
    //   },
    corner: {
      width: 45,
      height: 45,
      borderWidth: 2,
      borderColor: '#b8b5ae',
      position: 'absolute',
      backgroundColor: 'transparent',
    },
    bottomBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 32,
      paddingBottom: 16,
    },
    captureButton: {
      alignSelf: 'center',
    },
    captureOuter: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: 'white',
      justifyContent: 'center',
      alignItems: 'center',
    },
    captureInner: {
      width: 95,
      height: 95,
      borderRadius: 47.5,
      backgroundColor: '#121212',
      justifyContent: 'center',
      alignItems: 'center',
    },
    imageOuter: {
      width: 66,
      height: 66,
      borderRadius: 33,
      backgroundColor: 'white',
      justifyContent: 'center',
      alignItems: 'center',
    },
    imageInner: {
      width: 61,
      height: 61,
      borderRadius: 30.5,
      backgroundColor: '#121212',
      justifyContent: 'center',
      alignItems: 'center',
    },
    captureInnerMost: {
      width: 88,
      height: 88,
      borderRadius: 44,
      backgroundColor: 'white',
      justifyContent: 'center',
      alignItems: 'center',
    },
    menuContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 8,
      gap: 8,
      backgroundColor: '#1E1E1E',
      borderBottomColor: '#444',
      borderBottomWidth: 1,
    },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 16,
      backgroundColor: '#333',
    },
    activeMenuItem: {
      backgroundColor: '#444',
    },
    menuText: {
      marginLeft: 8,
      color: 'white',
      fontSize: 14,
      fontFamily: 'OpenSans-Regular',
    },
    lottieContainer: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: [{ translateX: -50 }, { translateY: -50 }],
      zIndex: 50,
    },
    lottieAnimation: {
      width: 150,
      height: 150,
      objectFit: 'contain'
    },
    bottomSheet: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: '#1E1E1E',
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 5,
      overflow: 'hidden',
      padding: 16,
    },
    sheetText: {
      fontSize: 16,
      color: '#555',
    },
  });